# Generated by Django 4.2.8 on 2026-02-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_requests", "0002_add_sla_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="first_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sla_pause_total_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sla_paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sla_response_breach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="sla_response_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
