const STATUS_CLASS = {
  critical: 'red',
  high: 'amber',
  medium: 'blue',
  low: 'green',
  breached: 'red',
  at_risk: 'amber',
  on_track: 'green',
  open: 'blue',
  in_progress: 'amber',
  resolved: 'green',
  closed: 'green',
  acknowledged: 'amber',
  assigned: 'amber',
  on_hold: 'amber',
  reopened: 'red',
  pending: 'amber',
  approved: 'green',
  rejected: 'red',
  draft: 'blue',
  submitted: 'amber',
  pending_approval: 'amber',
  fulfilled: 'green',
  completed: 'green',
  scheduled: 'blue',
  investigating: 'amber',
  diagnosed: 'amber',
  solution_identified: 'blue',
  identified: 'blue',
  active: 'green',
  inactive: 'amber',
  retired: 'red',
  planned: 'blue',
  degraded: 'amber',
  red: 'red',
  amber: 'amber',
  green: 'green',
  blue: 'blue',
}

export default function StatusChip({ label, tone }) {
  const className = STATUS_CLASS[tone] || 'blue'
  return <span className={`chip ${className}`}>{label}</span>
}
