# Generated by Django 5.2.11 on 2026-02-08 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '__first__'),
        ('organizations', '0002_departmentmember'),
        ('service_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('incident_category', models.CharField(blank=True, max_length=100)),
                ('applies_to_priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('response_time', models.IntegerField()),
                ('resolution_time', models.IntegerField()),
                ('coverage', models.CharField(choices=[('24x7', '24x7'), ('business', 'Business Hours (9-5)'), ('extended', 'Extended Hours (8-8)')], default='24x7', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='organizations.organization')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='service_requests.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('escalate_after_minutes', models.IntegerField()),
                ('notify_managers', models.BooleanField(default=True)),
                ('action_description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('escalate_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_incidents', to='organizations.team')),
                ('escalate_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_incidents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_escalations', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='sla.slapolicy')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='SLABreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('breach_type', models.CharField(choices=[('response', 'Response Time'), ('resolution', 'Resolution Time')], max_length=20)),
                ('target_time', models.DateTimeField()),
                ('breached_at', models.DateTimeField()),
                ('breach_duration_minutes', models.IntegerField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_breach_record', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_breaches', to='organizations.organization')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_breach_record', to='service_requests.servicerequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sla_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breaches', to='sla.slapolicy')),
            ],
            options={
                'ordering': ['-breached_at'],
            },
        ),
        migrations.CreateModel(
            name='SLATarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('response_time_minutes', models.IntegerField()),
                ('resolution_time_minutes', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sla_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sla.slapolicy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['severity'],
            },
        ),
        migrations.CreateModel(
            name='SLAMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_incidents', models.IntegerField(default=0)),
                ('breached_incidents', models.IntegerField(default=0)),
                ('compliance_percentage', models.FloatField(default=100.0)),
                ('target_compliance', models.FloatField(default=95.0)),
                ('is_compliant', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_metrics', to='organizations.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['organization', 'year', 'month'], name='sla_slametr_organiz_dee253_idx')],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['organization', 'is_active'], name='sla_slapoli_organiz_d9abbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slaescalation',
            unique_together={('sla_policy', 'level')},
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['organization', 'breach_type'], name='sla_slabrea_organiz_8e9c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['is_acknowledged'], name='sla_slabrea_is_ackn_fe8e85_idx'),
        ),
        migrations.AddIndex(
            model_name='slatarget',
            index=models.Index(fields=['sla_policy', 'severity'], name='sla_slatarg_sla_pol_b69be3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slatarget',
            unique_together={('sla_policy', 'severity')},
        ),
    ]
