# Generated by manual fix on 2026-02-08

from django.db import migrations


def create_slatarget_if_missing(apps, schema_editor):
    table_name = "sla_slatarget"
    if table_name in schema_editor.connection.introspection.table_names():
        return

    SLATarget = apps.get_model("sla", "SLATarget")
    schema_editor.create_model(SLATarget)


def drop_slatarget_if_exists(apps, schema_editor):
    table_name = "sla_slatarget"
    if table_name not in schema_editor.connection.introspection.table_names():
        return

    SLATarget = apps.get_model("sla", "SLATarget")
    schema_editor.delete_model(SLATarget)


class Migration(migrations.Migration):

    dependencies = [
        ("sla", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_slatarget_if_missing, drop_slatarget_if_exists),
    ]
