# Generated by Django 4.2.8 on 2026-02-15 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0004_rename_organizatio_organiz_1c4df5_idx_organizatio_organiz_055c45_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_requests", "0003_servicerequest_first_response_at_and_more"),
        ("sla", "0002_create_slatarget_table"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="slaescalation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="slaescalation",
            name="breach_type",
            field=models.CharField(
                choices=[
                    ("response", "Response Time"),
                    ("resolution", "Resolution Time"),
                ],
                default="resolution",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="applies_to_type",
            field=models.CharField(
                choices=[
                    ("incident", "Incident"),
                    ("service_request", "Service Request"),
                ],
                default="incident",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="incident_impact",
            field=models.IntegerField(
                blank=True, choices=[(1, "High"), (2, "Medium"), (3, "Low")], null=True
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="incident_urgency",
            field=models.IntegerField(
                blank=True, choices=[(1, "High"), (2, "Medium"), (3, "Low")], null=True
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sla_policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="requester_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sla_policies",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sla_policies",
                to="service_requests.servicecategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slaescalation",
            unique_together={("sla_policy", "level", "breach_type")},
        ),
    ]
