# Generated by Django 4.2.8 on 2026-02-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="knowledgearticle",
            new_name="knowledge_k_organiz_8b94b0_idx",
            old_name="knowledge_a_org_sta_28f9d4_idx",
        ),
        migrations.RenameIndex(
            model_name="knowledgearticle",
            new_name="knowledge_k_organiz_1701f2_idx",
            old_name="knowledge_a_org_cat_9c2c54_idx",
        ),
        migrations.RenameIndex(
            model_name="knowledgearticle",
            new_name="knowledge_k_updated_37b80a_idx",
            old_name="knowledge_a_upd_13a3a1_idx",
        ),
        migrations.AlterField(
            model_name="knowledgearticle",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgearticle",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
