# Generated by Django 4.2.8 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="csf_function",
            field=models.CharField(
                choices=[
                    ("govern", "Govern"),
                    ("identify", "Identify"),
                    ("protect", "Protect"),
                    ("detect", "Detect"),
                    ("respond", "Respond"),
                    ("recover", "Recover"),
                ],
                default="identify",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="csf_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="iso_control",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="knowledgearticle",
            name="nist_control",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
