# Generated by Django 4.2.8 on 2026-02-13 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_knowledge_iso_nist_fields"),
        ("knowledge", "0002_rename_knowledge_a_org_sta_28f9d4_idx_knowledge_k_organiz_8b94b0_idx_and_more"),
    ]

    operations = []
