# Generated by Django 4.2.8 on 2026-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0003_merge_0002_knowledge_iso_nist_fields_0002_rename_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
    ]
