# Generated by Django 4.2.8 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_ad_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("end_user", "End User"),
                    ("asset_manager", "Asset Manager"),
                    ("engineer", "Engineer"),
                    ("agent", "Agent"),
                    ("manager", "Manager"),
                    ("admin", "Administrator"),
                ],
                default="end_user",
                max_length=50,
            ),
        ),
    ]
