# Generated by Django 4.2.8 on 2026-02-14 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0004_rename_organizatio_organiz_1c4df5_idx_organizatio_organiz_055c45_idx",
        ),
        ("users", "0004_add_asset_manager_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="adconfiguration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adconfiguration",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="adconfiguration",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="auto_create_users",
            field=models.BooleanField(
                default=True, help_text="Automatically create users found in AD"
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="auto_disable_missing_users",
            field=models.BooleanField(
                default=False, help_text="Disable users not found in AD during sync"
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="auto_update_users",
            field=models.BooleanField(
                default=True, help_text="Automatically update user info from AD"
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="bind_password",
            field=models.CharField(
                help_text="Service account password", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="bind_username",
            field=models.CharField(
                help_text="Service account username (e.g., CN=admin,DC=company,DC=com)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="email_attribute",
            field=models.CharField(
                default="mail",
                help_text="AD attribute for email (typically mail)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="first_name_attribute",
            field=models.CharField(
                default="givenName",
                help_text="AD attribute for first name (typically givenName)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="group_base",
            field=models.CharField(
                blank=True,
                help_text="Base DN for group search (e.g., OU=Groups,DC=company,DC=com)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="group_member_attribute",
            field=models.CharField(
                default="member",
                help_text="Attribute that contains group members (typically member or memberUid)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="last_name_attribute",
            field=models.CharField(
                default="sn",
                help_text="AD attribute for last name (typically sn)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last successful sync", null=True
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="last_sync_error",
            field=models.TextField(
                blank=True,
                help_text="Error message from last sync (if failed)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="last_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="organization",
            field=models.OneToOneField(
                help_text="One AD config per organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_configuration",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="phone_attribute",
            field=models.CharField(
                default="telephoneNumber",
                help_text="AD attribute for phone (typically telephoneNumber)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="search_filter",
            field=models.CharField(
                default="(objectClass=user)",
                help_text="LDAP filter for users (default: (objectClass=user))",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="server_name",
            field=models.CharField(
                help_text="AD Server hostname or IP (e.g., 192.168.1.10 or ad.company.local)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="server_port",
            field=models.IntegerField(
                default=389, help_text="LDAP port (389 for plain, 636 for SSL)"
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="use_ssl",
            field=models.BooleanField(
                default=False, help_text="Enable SSL/TLS for secure connection"
            ),
        ),
        migrations.AlterField(
            model_name="adconfiguration",
            name="username_attribute",
            field=models.CharField(
                default="sAMAccountName",
                help_text="AD attribute for username (typically sAMAccountName)",
                max_length=50,
            ),
        ),
    ]
