# Generated by Django 5.2.11 on 2026-02-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0002_initial'),
        ('organizations', '0002_departmentmember'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cirelated',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AddField(
            model_name='cirelationship',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_relationships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cmdb.cicategory'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='owner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cis', to='organizations.team'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirelationship',
            name='source_ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='cmdb.configurationitem'),
        ),
        migrations.AddField(
            model_name='cirelationship',
            name='target_ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='cmdb.configurationitem'),
        ),
        migrations.AddField(
            model_name='cirelated',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='cmdb.configurationitem'),
        ),
        migrations.AddField(
            model_name='cichangehistory',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='cmdb.configurationitem'),
        ),
        migrations.AddField(
            model_name='ciattribute',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cmdb.configurationitem'),
        ),
        migrations.AlterUniqueTogether(
            name='cicategory',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['organization', 'status'], name='cmdb_config_organiz_c06bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['organization', 'category'], name='cmdb_config_organiz_71d61a_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['ci_number'], name='cmdb_config_ci_numb_88196c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationitem',
            unique_together={('organization', 'ci_number')},
        ),
        migrations.AddIndex(
            model_name='cirelationship',
            index=models.Index(fields=['source_ci', 'is_active'], name='cmdb_cirela_source__3f5dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='cirelationship',
            index=models.Index(fields=['target_ci', 'is_active'], name='cmdb_cirela_target__bc91a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cirelationship',
            unique_together={('source_ci', 'target_ci', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='cirelated',
            index=models.Index(fields=['ci'], name='cmdb_cirela_ci_id_e46eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='cichangehistory',
            index=models.Index(fields=['ci', '-created_at'], name='cmdb_cichan_ci_id_7afe4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ciattribute',
            unique_together={('ci', 'attribute_name')},
        ),
    ]
