# Generated by Django 4.2.8 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationitem",
            name="impact_analysis",
            field=models.TextField(blank=True),
        ),
    ]
