# Generated by Django 4.2.8 on 2026-02-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0004_add_ci_impact_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationitem",
            name="ci_class",
            field=models.CharField(
                choices=[
                    ("service", "Service"),
                    ("application", "Application"),
                    ("infrastructure", "Infrastructure"),
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("network", "Network"),
                    ("data", "Data"),
                    ("documentation", "Documentation"),
                    ("other", "Other"),
                ],
                default="service",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="configurationitem",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="configurationitem",
            name="last_audit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configurationitem",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="configurationitem",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("design", "Design"),
                    ("build", "Build"),
                    ("test", "Test"),
                    ("in_operation", "In Operation"),
                    ("deprecated", "Deprecated"),
                    ("retired", "Retired"),
                ],
                default="in_operation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="configurationitem",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending_review", "Pending Review"),
                    ("verified", "Verified"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
    ]
