# Generated by Django 5.2.11 on 2026-02-08 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changes', '0001_initial'),
        ('organizations', '0002_departmentmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('investigating', 'Investigating'), ('diagnosed', 'Diagnosed'), ('solution_identified', 'Solution Identified'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='identified', max_length=20)),
                ('affected_users', models.IntegerField(default=0)),
                ('affected_services', models.CharField(blank=True, max_length=500)),
                ('root_cause', models.TextField(blank=True)),
                ('workaround', models.TextField(blank=True)),
                ('permanent_solution', models.TextField(blank=True)),
                ('first_incident_date', models.DateTimeField(blank=True, null=True)),
                ('identified_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('change_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem', to='changes.change')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='organizations.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_problems', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnownErrorDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('error_code', models.CharField(max_length=50, unique=True)),
                ('symptoms', models.TextField()),
                ('workaround', models.TextField()),
                ('permanent_solution', models.TextField(blank=True)),
                ('resolution_rate', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_errors', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('problem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kedb_entry', to='problems.problem')),
            ],
            options={
                'verbose_name_plural': 'Known Error Databases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('investigation_method', models.CharField(blank=True, max_length=100)),
                ('five_whys', models.TextField(blank=True)),
                ('contributing_factors', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rca', to='problems.problem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Root Cause Analyses',
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['organization', 'status'], name='problems_pr_organiz_93e3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['ticket_number'], name='problems_pr_ticket__c7d965_idx'),
        ),
        migrations.AddIndex(
            model_name='knownerrordatabase',
            index=models.Index(fields=['organization'], name='problems_kn_organiz_2d53cb_idx'),
        ),
        migrations.AddIndex(
            model_name='knownerrordatabase',
            index=models.Index(fields=['error_code'], name='problems_kn_error_c_3402fe_idx'),
        ),
    ]
