# Generated by Django 4.2.8 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_rename_assets_asset_org_sta_4f9d2c_idx_assets_asse_organiz_ad90f0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("virtual", "Virtual"),
                    ("network", "Network"),
                    ("data", "Data"),
                    ("service", "Service"),
                    ("facility", "Facility"),
                    ("other", "Other"),
                ],
                default="hardware",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("acquisition", "Acquisition"),
                    ("in_use", "In Use"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                    ("disposed", "Disposed"),
                ],
                default="in_use",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="business_owner",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="technical_owner",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="related_service",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="system_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="data_classification",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("internal", "Internal"),
                    ("confidential", "Confidential"),
                    ("restricted", "Restricted"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="confidentiality_impact",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="integrity_impact",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="availability_impact",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="fips_impact_level",
            field=models.CharField(
                choices=[("low", "Low"), ("moderate", "Moderate"), ("high", "High")],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="recovery_priority",
            field=models.CharField(
                choices=[
                    ("p1", "P1 - Critical"),
                    ("p2", "P2 - High"),
                    ("p3", "P3 - Medium"),
                    ("p4", "P4 - Low"),
                ],
                default="p3",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="business_value",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="authorization_boundary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="dependencies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="compliance_tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
