# Generated by Django 5.2.11 on 2026-02-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0001_initial'),
        ('service_requests', '0002_add_sla_policy'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='change_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='changes.change'),
        ),
    ]
