# Generated by Django 5.2.11 on 2026-02-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_departmentmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('incidents', 'Incidents'), ('service_requests', 'Service Requests'), ('problems', 'Problems'), ('changes', 'Changes'), ('assets', 'Assets')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_categories', to='organizations.organization')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'module', 'name')},
                'indexes': [models.Index(fields=['organization', 'module', 'is_active'], name='organizatio_organiz_1c4df5_idx')],
            },
        ),
    ]
