# Generated by Django 4.2.8 on 2026-02-14 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_modulecategory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="modulecategory",
            new_name="organizatio_organiz_055c45_idx",
            old_name="organizatio_organiz_1c4df5_idx",
        ),
    ]
