# Generated by Django 5.2.11 on 2026-02-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('organizations', '0002_departmentmember'),
        ('problems', '0001_initial'),
        ('sla', '0002_create_slatarget_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='related_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_incidents', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='incident',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='sla.slapolicy'),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentmetric',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentmetric',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_metrics', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='incidentworkaround',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentworkaround',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workarounds', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incidentworkaround',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'status'], name='incidents_i_organiz_09b358_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'priority'], name='incidents_i_organiz_7dfa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['ticket_number'], name='incidents_i_ticket__1730b3_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assigned_to', 'status'], name='incidents_i_assigne_f40e13_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['sla_breach', 'status'], name='incidents_i_sla_bre_c1dae0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='incidents_i_created_c4c91a_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentcomment',
            index=models.Index(fields=['incident', 'is_internal'], name='incidents_i_inciden_c4d255_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentmetric',
            index=models.Index(fields=['organization', '-created_at'], name='incidents_i_organiz_4b7956_idx'),
        ),
    ]
