# Generated by Django 4.2.8 on 2026-02-13 00:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("incidents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="is_major",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="major_incident_level",
            field=models.CharField(blank=True, choices=[("mi1", "Major 1 (Critical)"), ("mi2", "Major 2 (High)"), ("mi3", "Major 3 (Medium)")], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="escalation_status",
            field=models.CharField(choices=[("not_escalated", "Not Escalated"), ("escalated", "Escalated"), ("de_escalated", "De-escalated")], default="not_escalated", max_length=20),
        ),
        migrations.AddField(
            model_name="incident",
            name="major_incident_manager",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="major_incidents", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="incident",
            name="communication_cadence_minutes",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="incident",
            name="next_communication_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="ola_target_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="uc_target_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="ola_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="uc_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="ola_breach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="uc_breach",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="IncidentCommunication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS"), ("portal", "Portal"), ("chat", "Chat"), ("call", "Call"), ("meeting", "Meeting")], max_length=20)),
                ("audience", models.CharField(choices=[("internal", "Internal"), ("external", "External"), ("executive", "Executive")], max_length=20)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("incident", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="communications", to="incidents.incident")),
                ("sent_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incident_communications", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
