# Generated by Django 4.2.8 on 2026-02-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("incidents", "0003_itil_major_incident_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="pir_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="pir_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not Required"),
                    ("pending", "Pending"),
                    ("in_review", "In Review"),
                    ("completed", "Completed"),
                ],
                default="not_required",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="pir_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="pir_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="pir_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pir_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="pir_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
