# Generated by Django 4.2.8 on 2026-02-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0004_post_incident_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="sla_coverage",
            field=models.CharField(
                choices=[
                    ("24x7", "24x7"),
                    ("business", "Business Hours (9-5)"),
                    ("extended", "Extended Hours (8-8)"),
                ],
                default="24x7",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="sla_pause_total_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incident",
            name="sla_paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="sla_response_breach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="sla_response_due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
